name: Auto Docker Build & Publish on Github Repo
on:
  push
jobs:
  Dkr_Build_And_Publish:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}    
    steps:
    - uses: actions/checkout@v4    
    - name: Build and Publish Docker Image 
      run: | 
          docker login --username aamirali310 --password ${{ secrets.AA_PCS_PAT }} ghcr.io          
          docker build . --tag ghcr.io/aamirali310/python-cheatsheet:latest
          docker push ghcr.io/aamirali310/python-cheatsheet:latest
