name: Auto Docker Build & Publish on Github Repo

on:
  push

jobs:
  Dkr_Build_And_Publish:
    runs-on: unbuntu-latest
    steps:
      -uses: Actions/checkout@latest
      -name: Build and Publish Docker Image 
        run: | 
          docker login --username aamirali310 --password ${{ secrets.AA_PCS_PAT }} ghcr.io
          docker build . --tag ghcr.io/aamirali310/python_cheatsheet@latest
          docker push ghcr.io/aamirali310/python_cheatsheet@latest
